### ISSUE TITLE
Is this still believed to work? :)

### ISSUE THREAD

**Issue by eseidelGoogle** [redonkulus/org-commits#1]
```
% org-commits -a $ACCESS_TOKEN -o flutter -d "1 month"
(node:74997) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: No repos found for flutter
(node:74997) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

I generated the token from:
https://github.com/settings/tokens
initially with no permissions, then regenerated with the "read public repositories permission", didn't seem to change anything.

**Comment by redonkulus** [comment]
@eseidelGoogle thanks for the report. Looks like its broken for the public github instance. I typically use this internally against our GitHub Enterprise instance so I didn't hit this issue. I'm working on updating the script, should be fixed soon.

**Comment by redonkulus** [comment]
@eseidelGoogle version 1.0.0 has been published. Please install the latest version and try again. Let me know if you still see any issues. Thanks!

**Comment by redonkulus** [comment]
@eseidelGoogle I also updated the docs to point to the Personal Access Token GitHub page to make it clearer.

**Comment by eseidelGoogle** [comment]
Fantastic.  Thank you very much!
