### ISSUE TITLE
org-commits barfs on fuchsia-mirror?

### ISSUE THREAD

**Issue by eseidelGoogle** [redonkulus/org-commits#5]
```
org-commits -a $TOKEN -o fuchsia-mirror -d "6 months"
(node:1800) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): {"message":"Git Repository is empty.","documentation_url":"https://developer.github.com/v3"}
(node:1800) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Not really sure why.

`org-commits -a $TOKEN -o flutter -d "6 months"` for example works just fine.

This is far from critical, just thought you might like to know.

**Comment by redonkulus** [comment]
Thanks for the heads up. I will take a look.

**Comment by redonkulus** [comment]
@eseidelGoogle debugged this more, the issue was that some repositories in `fuchsia-mirror` were empty and the GitHub API was returning an error. This was causing `org-commits` to fail. Now instead of failing silently, I `console` the error so that it can be discovered. This is released in v1.2.1.

**Comment by eseidelGoogle** [comment]
I believe you're the most responsive owner of a random github tool I've yet to run across. :)  Thank you kindly!

**Comment by redonkulus** [comment]
I will wear that honor proudly haha. Let me know if anything else comes up.
